### ISSUE TITLE
Adjust front-end code to honour DOB & DOD from wikidata

### ISSUE THREAD

**Issue by dshorthouse** [rdmpage/alec#15]
The `isodate_to_string` function in utils.ejs parses a Date and then presents it using `d.toLocaleString('en-gb', options)`. Unfortunately, the source date for DOB and DOD do not have a timezone 'en-gb' and so the presentation of DOB and DOD can both be off by a day, depending on the client's timezone. The discrepancy *might* be overcome by getting the offset: `offset = new Date().getTimezoneOffset()` (untested). The screenshot below from a client browser in EDT shows incorrect DOB/DOD, which are actually 27 August 1913 and 30 May 2008, respectively.
<img width="746" alt="Screen Shot 2021-08-31 at 9 57 40 PM" src="https://user-images.githubusercontent.com/326459/131599974-2159d630-306c-42be-8d22-da308ac15532.png">

**Comment by dshorthouse** [comment]
Might be something here https://stackoverflow.com/questions/15141762/how-to-initialize-a-javascript-date-to-a-particular-time-zone

**Comment by rdmpage** [comment]
@dshorthouse OK I've added UTC as a timezone to see if that makes a difference, try https://alec-demo.herokuapp.com/Q3286276 I confess I've not tested this (will need to think about how to test across timezones).

**Comment by dshorthouse** [comment]
Cool! Will check it from my end in NA when the date rolls over at yours and will post back.

**Comment by dshorthouse** [comment]
Forgot to mention that you can do this via https://www.webpagetest.org/. I just tried now at handful of locations in the world & the screenshots appear to consistently show the same date. Here's the output from Sydney https://www.webpagetest.org/result/210922_AiDcRB_d696eaa001688470b9dd1554c21c556e/

**Comment by dshorthouse** [comment]
All good!

**Comment by rdmpage** [comment]
@dshorthouse many thanks for testing this. I'll close the issue, then open a new one to remind me to investigate the other things raised by the results from webpagetext.org.
