### ISSUE TITLE
OpenGraph URLs are encoded as HTML entities

### ISSUE THREAD

**Issue by larsgw** [rdmpage/alec#7]
When I visit view-source:https://alec-demo.herokuapp.com/Q106624676 I see the following:

```html
<meta property="og:type" content="website" />
<meta property="og:url" content="http&colon;&sol;&sol;alec-demo&period;herokuapp&period;com&sol;Q106624676" />
<meta property="og:image" content="http&colon;&sol;&sol;alec-demo&period;herokuapp&period;com&sol;image&period;php&quest;qid&equals;Q106624676" />
```

I think this breaks OpenGraph. I think the code needs to call `htmlspecialchars` instead of `htmlentities`: https://stackoverflow.com/a/46491/5095300

https://github.com/rdmpage/alec/blob/0146a31c9c47bfe32aeb67fc2311a4c3a15f1d60/index.php#L129

**Comment by rdmpage** [comment]
Fixed with 517292f63b1826ac14806db1b6709fc89b969639
