### ISSUE TITLE
Manuscript comments

### ISSUE THREAD

**Issue by larsgw** [rdmpage/alec#8]
Some small issues I saw in the preprint:

  - Figure 1: the lower half labels of the top-level properties, especially P50 and P2860 are very close to the arrow above them (the wrong one). This was a bit confusing to me for a second.
  - > If it is not known whether the author exists in Wikidata their name can be stored as a simple string value (P1545).
    
    I think this should say P2093.
  - The (Bohannon, 2016) reference is a bit messed up ("(BohannonApr. 28, 2016, ...)").
  - The (Page) reference (i.e. the GBIF dataset) might benefit from a year? Unless it was omitted on purpose of course.
  - > ... CiteProc JSON, a default standard for bibliographic metadata that originates in the Zotero project (https://www.zotero.org/).
    
    I am pretty sure that CiteProc JSON [originates from citeproc-js](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html) and is currently maintained by the [Citation Style Language](https://github.com/citation-style-language/schema#csl-json-schema) project.

**Comment by rdmpage** [comment]
@larsgw Thanks for these comments, I'm incorporating them into a revised version.
